### ISSUE TITLE
Unable to change the layout of binding associations

### ISSUE THREAD

**Issue by juli1** [osate/osate-ge#102]
This is not possible to move the arrows of a binding and not even possible to stretch of modify it. Arrows that represent bindings are straight and cannot be flexible. However, it would be great to have a more flexible layout for bindings associations

**Comment by philip-alldredge** [comment]
So to be clear, what kind of flexibility would you like? In the short term, I'm not sure how much can be done, but longer term it would be helpful to prioritize improvements. Currently the binding association connections are just simple visualization and not something that can be edited besides toggling them on and off, etc.

**Comment by juli1** [comment]
Have the same edition capability than the features connections: change the location within the component, move the arrow around components, etc.

**Comment by juli1** [comment]
The issue is that because we cannot change the layout and move the arrow, it overlaps with other elements, which can then make the graphical model messy.

**Comment by philip-alldredge** [comment]
Understood. This is definitely something that would be nice for the future. However, in the short term, the best option is to disable the bindings (through the diagram's properties) to avoid clutter.

Implementation Note:
In the future moving to a mechanism where binding associations are not transient will be needed.

**Comment by philip-alldredge** [comment]
Closing. This will be implemented as part of #164.
