### ISSUE TITLE
OSATE Bind Dialog Box Error

### ISSUE THREAD

**Issue by kjherring** [osate/osate-ge#118]
When using the “Bind” Dialog box, I select a Virtual Processor to bind to a Processor using Actual_Processor_Binding property. Click [OK] 

I receive this message: “One or more selected target  elements are invalid.” What is added to the declarative model is:
Actual_Processor_Binding => () applies to VP1; -- note the missing reference() to a processor
Additionally,  the diagram does not display a dashed line with an arrow.

This is what should be added to the declarative model:
 Actual_Processor_Binding => (reference (thisProcessor)) applies to VP1;

When I manually add the following to the declarative model:
Actual_Processor_Binding => (reference (thisProcessor)) applies to VP1;
 
The diagram displays a dashed line with an arrow correctly, with no errors noted.

OSATE Version: daily 08/18/2015
Java Version: 1.8.0_31-b13
Windows Version: 7 Professional, SP1

**Comment by philip-alldredge** [comment]
Fixed in a22f6983b0d1ba5ec192abbf8de3efa5e419e880.
