### ISSUE TITLE
Dialog for end to end flow creation doesn't show sequence of selected elements (Linux)

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#122]
The flow creation dialog should show the names of the elements selected so far. That works on Windows, but on Linux no text is shown. Maybe the contained text area needs to be set to fill the available space. IIRC, we had a similar issue in the AADL properties view where we needed to add SWT.FILL or something like that.

OSATE 2.1.2 on Kubuntu 15.04

**Comment by lwrage** [comment]
I've fixed the layout such that it works on Linux. Needs to be tested on Windows and OS X.

**Comment by philip-alldredge** [comment]
Works on windows.
