### ISSUE TITLE
NPE in new model in new workspace

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#128]
This was in a fresh empty workspace, originally on linux, reproduced on Mac. Nightly version built on 9/28/15:
Create a new project named test, create an aadl file named test.aadl with content
```
package test
public
  system S
  end S;

  system implementation S.i
  end S.i;
end test;
```

Move cursor inside word test in first line, right click and select Open Diagram -> exception, no diagram created.
After this we could not create any diagrams, neither from text editor nor form the outline.

**Comment by philip-alldredge** [comment]
I am unable to reproduce the issue. Can you provide a copy of the exception?

**Comment by lwrage** [comment]
I can't reproduce this either. Unfortunately the log files are gone.

**Comment by philip-alldredge** [comment]
Okay. Let me know if it occurs again.
