### ISSUE TITLE
Link with editor has no effect for graphical editor

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#131]
Turning on "link with editor" in the AADL navigator has no effect. If should highlight either the current diagram file of the current AADL file.

![snapshot1](https://cloud.githubusercontent.com/assets/750311/10176757/921fd048-66c4-11e5-8f9f-d5886a15a826.png)

**Comment by philip-alldredge** [comment]
Fixed in cf12d2cbe59a262ddc405d05a8da01da4cb21c13.
