### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate-ge#138]
The editor experiences significant slowdown with more complex models and when increasing the nesting level. Profile and improve performance.

**Comment by juli1** [comment]
What changes have you done to improve the performances? I am interested by the details - especially what was slowing the editor.

**Comment by philip-alldredge** [comment]
Tthe following was done:
* Improved the reference mechanism to support project references and other edge cases. The intention wasn't to improve performance, but there are some cases where I believe it is faster. 
* Improved how updates are performed on shapes. There were some cases where an update would trigger an update to children or parents needlessly.  This is big source of improvement. The update code very often so any improvement should help overall.
* When a layout is performed, avoid redrawing when a single diagram element is moved. This was originally part of a workaround for a Graphiti bug that causes objects to be drawn incorrectly, but was causing performance issues in conjunction with layout. The workaround is still in the code, but is only done once after the entire update is completed.
* Reworked the layout algorithm. The new one is much simpler. The automatic layout is something that needs more work, but the simpler algorithm is consistent and faster. Especially when working with larger models. The layout algorithm is something that is called anytime a new diagram is created or a shape is added based on a change to the aadl source.

There are sure to be other things that need to be improved. If you have specific models that you can make available to me that are still are a source of frustration, let me know and I can look at them specifically.

**Comment by juli1** [comment]
Sounds great! I can't wait to try!
