### ISSUE TITLE
Extend Graphical Editor EMV2 Support

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate-ge#147]
> edit EMV2 error types and state machines.

Expand EMV2 support plugin capabilities and bring it up to date with graphical editor user interface and internal implementation improvements.

Look at support in IMV support for EMV2. Providing similar capabilities is critical for having a unified graphical editor and viewer.

Should also consider supporting EMV2 libraries and clauses which are in their own file.  See osate/osate2-core#903

**Comment by lwrage** [comment]
For subclauses it's one file per AADL package.
Note that storage in separate files will be disabled by default as it doesn't conform to the AADL standard. The user must enable support by changing a preference setting.
