### ISSUE TITLE
Copy/paste of model elements in graphical editor

### ISSUE THREAD

**Issue by reteprelief** [osate/osate-ge#15]
Sometimes it is desirable to make a copy of a classifier with all its parts, e.g., a device type with all its ports.

**Comment by philip-alldredge** [comment]
The editor needs to support copy and pasting of model elements.

Need to define a set of goals for the feature which will be achievable. Need to be practical. 
- Have option for just copying presentation between diagrams?
- Copy top level model elements and then just copy presentation for lower elements.
- IDEA: Copying multiple elements: If a connection and other elements are copied, pasting should update the references in the connection(s) to point to the new elements.
