### ISSUE TITLE
Basic Formatting Support

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate-ge#151]
> capability to customize the colors, line sizes, and font sizes used to represent model elements.

Add ability for user to customize the style of individual portions of the diagram.

Specifically:
- Outline Color
- Fill Color
- Text Color
- Line/Connection Size
- Adjust font size. Either specific or relative(small or large). Consider DPI issues.

Consider conflicts with flow and mode coloring. Decide how to handle. May just need to leave it up to the user.

**Comment by brlarson** [comment]
Fill color should have priority.

**Comment by philip-alldredge** [comment]
Implemented in 342fefb047ee3a1ac02991bac8ec7c9dd22eded6.
