### ISSUE TITLE
Use Image for Shape

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate-ge#154]
> capability to use a referenced image file as a background for a model element

Attach pictures, e.g. to system blocks to represent the system, e.g. a plane, a wheel, etc.

**Comment by RyanMcilnay** [comment]
TODO
- Test behavior when image file itself is updated. Will need to refresh image.
- Ensure freed when no longer referenced.	
- Don't register the same image ID multiple times.

**Comment by philip-alldredge** [comment]
- LayoutUtil.layout() - Create platform graphics algorithm instead of the one specified by the graphical configuration.
- Only support image for shape graphics which do not have a dock area.
- Layout algorithm should be adjusted to avoid resizing diagram elements which have an image.

**Comment by philip-alldredge** [comment]
- Add an option to the style and XML to show as image. If this is enabled, the image is used. If not, then the default representation is used. It should be automatically enabled when the user selects an image. This will allow the user to quickly switch between the standard and the image representation as desired. This is similar to functionality provided by other tools.

**Comment by philip-alldredge** [comment]
- AgeDiagramTypeProvider
	- Add a public static method getResources() that returns a resource manger. Delegate to JFaceResources.getResources().
- GraphitiAgeDiagram
	- Owns a local resource manager. Parent should be result of AgeDiagramTypeProvider.getResources()
	- Closing GraphitiAgeDiagram should dispose the local resource manager.	
	- During update process(beforeModificationsCompleted()). Create a new local resource manager and pass it to LayoutUtil. Before ending the update process, dispose of the old resource manager and keep a reference to the new local resource manager.
- LayoutUtil
	- Will used the passed in resource manager to load image.	
	- Will set the ga's image property to the project independent path which can be used to build the image descriptor.
	- Will use methods in PathUtil to convert path as appropriate
- GA Renderer Factory
	- Will use AgeDiagramTypeProvider.getResources() to retrieve already loaded image. Handle gracefully if it isn't loaded. Do not load.
- Style
	- Will store a path relative to the project in which the diagram is stored.
- org.osate.ge.internal.util.PathUtil
	- Create class	
	- Add a public static methods for converting path to project relative to path. Use for determing path to store in project. 
	- Add a public static method for converting a path to a workspace relative path.
	- See IPath's makeAbsolute(), makeRelativeTo(), toOSString(), toPortableString().
- Test on Windows and Linux
