### ISSUE TITLE
Negative Y-coordinate values for feature groups

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#172]
A report from a user: Sometimes, the OSATE diagram layout engine assigns a negative value to the y value of a feature group for a component.  Since the feature group is in the negative space it can’t be moved in the diagram.  You can view the diagram as text and update the XML to change negative y values to positive values.

**Comment by philip-alldredge** [comment]
Do you have any information about how to reproduce this one? Once development resumes I can spend additional time trying to reproduce things, but it would speed things along if there was a reliable way to reproduce this. Are you aware of which version of OSATE the user is using? Unless noted, I will assume the latest.

**Comment by lwrage** [comment]
Unfortunately, I don't know how to reproduce it. The user observed it with OSATE 2.2.1 update01.

**Comment by philip-alldredge** [comment]
I've been unable to reproduce this issue. As a solution until such time that the issue can be reproduced, I have updated the editor to ensure that feature Y values are >= 0 when the diagram element for the feature is updated.
