### ISSUE TITLE
Loosen Up Editing Rules

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate-ge#193]
> Support for editing classifiers in the context of diagram elements representing sub-components, component implementations, and feature groups.

Since the initial version of the graphical editor there have been restrictions regarding when the user can create, edit, and delete diagram elements. These were put in place so that the graphical editor remained a 1 to 1 mapping between diagrams and the declarative model. These restrictions result in a tedious user experience and are more so when coupled with diagrams which support multiple levels of subcomponents.

The plan is to allow the user to create, editing and delete in whatever context is desired. The exact design is TBD. However, overall goal is to allow the user flexibility, but to keep the user informed and in control of the model modifications being performed. For example, if the user adds a child to a subcomponent graphically, the user should be given the option to select the model element to be modified when multiple options exist. We will want to avoid prompts when possible but they should be considered if necessary. If the user is constantly bombarded with confirmation prompts, the user is more likely to feel that the tool is fighting with them. 

- Editing type when looking at a subcomponent #82
- Editing refined elements when editing something other than the element which owns it. 
- Creating features from the classifier view.
- This should include editing feature group types by editing feature groups. 
- Should be able to refine elements inside a subcomponent.

Ideas:
- When creating elements which could have multiple potential owners, allow the user to select which one. In the case of subcomponents, the user will need the option to create a new classifier as well. This should include creation of flow implementations as well.
- Option to create new implementation/feature group type menu option for subcomponents and feature group.

Other:
- Don't allow changing contributed resources

**Comment by smithdtyler** [comment]
How do you plan to handle diagram comments/annotations?

**Comment by philip-alldredge** [comment]
@smithdtyler this comment seems more appropriate for #187. The capability is near the end of the roadmap so we don't have a firm design at the moment.  If you have particular requirements you'd like to see with that capability, please add comments to that issue.

**Comment by philip-alldredge** [comment]
## Capabilities
The planned capabilities are listed below.
- [ ] Create a new type / implementation for a subcomponent. Default to extending existing classifier.
- [ ] Create feature group type for feature group. Default to existing existing feature group type.
- [ ] Add feature, sucomponents, etc to subcomponent. Prompt if ambiguous. Prompt if no existing classifier.
- [ ] Add features to component implementations. #82. Prompt if type is ambiguous.
- [ ] Add features to feature groups. Prompt if feature group type doesn't exist.
- [ ] Delete an unrefined element from any context. Notify user.
- [ ] Rename an unrefined element from any context. Notify user.
- [ ] Refine elements from inside a subcomponent. Change is made to the subcomponent's classifier.
- [ ] Ensure that the user cannot attempt to modify contributed resources.

## Misc
Ensure functionality works when types, implementations, etc are located in another package/file.
