### ISSUE TITLE
Tidy Feature

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate-ge#208]
Line up features which have connections between them and any other formatting changes that are commonly performed.

**Comment by smithdtyler** [comment]
I suggest offering "align top", "align bottom", tidy features to line up boxes. These are offered in Enterprise Architect and I use them constantly.

**Comment by philip-alldredge** [comment]
@smithdtyler this issue is tracking a "tidy" tool that will automatically line up boxes as it sees fit. Improvements to the alignment tools such as "align top", "align bottom" are on the roadmap and are being tracked by #204. They currently do not work with features or diagram elements which different parents.
