### ISSUE TITLE
Provide opaque or obscuring background for text labels

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate-ge#221]
Textual labels should obscure or hide graphical elements behind them. Here's an example from Enterprise Architect. Note that the label hides the line behind it so the text does not collide with the line. 

![screen shot 2017-09-22 at 3 34 57 pm](https://user-images.githubusercontent.com/8142684/31099222-e2f73e76-a78a-11e7-9db7-b84bda2694cf.png)

**Comment by smithdtyler** [comment]
Screenshot example of the problem:

![screen shot 2017-10-02 at 4 29 49 pm](https://user-images.githubusercontent.com/8142684/31100413-f48b34d6-a78e-11e7-96e7-dbe991336bc5.png)

**Comment by philip-alldredge** [comment]
If I recall correctly there were implementation issues that prevents this from being implemented.  We'll need to revisit if we move to GEF5.

**Comment by philip-alldredge** [comment]
I looked at it again and the problem is that although the text can be assigned a background color, it does not obscure the connection. I believe this is due to Graphiti's use of GEF3. I believe GEF3 separates connections into their own layer which are rendered on top.

**Comment by philip-alldredge** [comment]
Recommend waiting until migration to GEF5.
