### ISSUE TITLE
Shrink line endings

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate-ge#224]
Line ending arrows are unnecessary large and make it easy for modestly complex components to become hard to read. 

![screen shot 2017-10-02 at 4 15 34 pm](https://user-images.githubusercontent.com/8142684/31099861-0b8813f4-a78d-11e7-95f4-b4fca091fdb3.png)

**Comment by philip-alldredge** [comment]
What do you mean by "line ending arrows"? Are you referring to the event data ports?

**Comment by smithdtyler** [comment]
Yes, the event data ports. In the picture I provided, it's the icon directly under the word "pasta" in "PastaProcessOutput"

**Comment by philip-alldredge** [comment]
I haven't experienced them being unnecessarily large in my opinion but I will look into shrinking event data ports and event ports to match the size of data ports. I'll likely implement it if there aren't any unforeseen issues. As it is, switching the type of the port results in a change of size which could shift other ports.

**Comment by philip-alldredge** [comment]
This is being rolled into for discussion as part of #228.
