### ISSUE TITLE
Autosize components to fit labels

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate-ge#227]
The default size for a component should be large enough to show its label without line collisions. 

![screen shot 2017-10-02 at 4 31 06 pm](https://user-images.githubusercontent.com/8142684/31100465-1ae8b7fc-a78f-11e7-9123-aaec215fd395.png)

**Comment by philip-alldredge** [comment]
Agreed

**Comment by lwrage** [comment]
Also, the text label areas are much larger than necessary, see the greyed out lines after ...impl.

**Comment by philip-alldredge** [comment]
Unfortunately the larger text labels than necessary *appears* to be a bug in one of the underlying Eclipse library. The editor was previously sizing the label based on the current font and text being rendered and that resulted in labels being truncated in many cases based on the zoom level. I imagine it is a floating point vs integer sizing issue somewhere in the chain. The only work around that was found was to pad the label size.

**Comment by philip-alldredge** [comment]
Note to implementer:
A mechanism is needed to adjust how the minimum size and the position offset for labels and other contents for an element based on the graphic type.
