### ISSUE TITLE
Flow Specifications are Hard to Distinguish from Connections

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate-ge#277]
Flow specifications are hard to distinguish from connections, but there are cases where both are shown for the same component implementation or subcomponent. To help alleviate the issue, increase the default line size for flow specifications. The line size will still be adjustable by the user.

**Comment by lwrage** [comment]
I would prefer to have dotted or dashed lines for flow specs.

**Comment by philip-alldredge** [comment]
My concern with dotted or dashed lines is that they are already used in the graphical editor. 

Of course, since line thickness is configurable, the user could configure a connection to look like a flow specification. So neither way provides an non-ambiguous representation. We were leaning toward/experimenting with solid lines because it matches what is in the standard and could be adjusted by the user if they preferred regular line thickness.

I'll experiment with some of the other lines styles and see how close they are to each other.
