### ISSUE TITLE
Wrong icons for access features

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#304]
Icons in OSATE don't conform to the AADL standard.
![15196799187241443617919](https://user-images.githubusercontent.com/750311/36695940-be94d95e-1b10-11e8-8fbc-c25626bbff55.jpg)

**Comment by lwrage** [comment]
I fixed the icons in the outline, and the same icons are used in the palette. This leaves the issue that data access features are not filled in the graphical editor.

**Comment by philip-alldredge** [comment]
Do you have a reference? It may be an inconsistency in the standard or perhaps I'm looking at an older version.  

"The same symbol is used to represent access to bus and to data. Figure 35 illustrates the graphical notation to represent sharing of data." Figure 35 does not show it as filled.

**Comment by lwrage** [comment]
8.6 figure 12. At the SEI we have always used the version from that diagram. I'm not sure what was intended. The AADL book uses the outline version for both, so we can just standardize on that for OSATE. I'll adjust the icons to match the graphical editor.
