### ISSUE TITLE
Navigate to diagrams containing the classifier type of subcomponents which have a component implementation classifier

### ISSUE THREAD

**Issue by reteprelief** [osate/osate-ge#62]
If I am in an implementation I may need to fix a feature of a subcomponent, e.g., change the data type or change it from data port to event data port.
It would be nice to have a goto Type in the graphical editor to edit the features graphically.

**Comment by philip-alldredge** [comment]
A goto type diagram command was merged in d55e5b2a745538de0840c8630b685f2300095beb. In the future we are planning to loosen up editing rules to allow editing features from different contexts(with the appropriate indicators about the implications).
