### ISSUE TITLE
Edit type when seeing subcomponents

### ISSUE THREAD

**Issue by reteprelief** [osate/osate-ge#82]
When in an implementation we can add connections between components, but we cannot add flow specs to the subcomponents when getting ready to specify end to end flow.
You have to go to the type and do it there - but the user has to know that.

We could offer a edit flows command in the context menu that effectively is the same as double clicking to go to the type. People will look for a command and thus look in the menu :-)

Same occurs when people want to add ports and are in the package view. In other editors you have been able to drop ports onto the classifier.
Either we offer that or play the trick of adding a command in the menu that effectively leads you to the open type.

**Comment by philip-alldredge** [comment]
Closing. This will be looked at as part of #193.
