### ISSUE TITLE
in modes editing improvement

### ISSUE THREAD

**Issue by reteprelief** [osate/osate-ge#89]
from course participants:
It would be nice to identify the elements that are part of a mode graphically rather than through the dialog.
I would like to select the mode for which I want to identify the elements in the model. Once selected I want issue a command (edit mode) to select the elements that are/are not part of the mode.
I would do so by clicking on the element (connection, subcomponent) to indicate that it should become part of the mode if not and vice versa.
Once done I issue a command to exit from this edit mode.

**Comment by philip-alldredge** [comment]
Closing. This is not planned to be implemented although it could be in the future. 

The new mode selection capability is much less cumbersome than the previous capability. It allows the user to select multiple elements and then specify the mode(s) to which they belong. So adding a group of elements to a mode is just a matter of selecting them graphically or from the outline and checking the box for the particular mode. Only the checked mode is modified so it handles the selection being in different modes properly.

Please reopen if the re-worked mode specification is not sufficient.
