### ISSUE TITLE
improvements to the flow editor

### ISSUE THREAD

**Issue by reteprelief** [osate/osate-ge#90]
from the course participants:
I would like to graphically identify the elements of a flow as alternative to the current dialog.
For flow implementations I would like to issue an edit command and then be in an edit mode in whihc I simply click on the elements involved in the flow implementation.
Similarly, for end to end flows, I may want to do it for an existing flow or create a new flow and then identify the elements of the flow by simply clicking on the model elements.

**Comment by philip-alldredge** [comment]
Implemented in 5f547d601bb8cbc506f6436819bd336dc6867a1f.
